// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ERRORS_COBOTMSGS_H_
#define FLATBUFFERS_GENERATED_ERRORS_COBOTMSGS_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

namespace CobotMsgs {

enum ErrorCode : int8_t {
  ErrorCode_ERR_OTHER = 0,
  ErrorCode_ERR_MALFORMED_REQUEST = 1,
  ErrorCode_ERR_OUT_OF_RANGE = 2,
  ErrorCode_ERR_INVALID_JOINT = 3,
  ErrorCode_ERR_NOT_INITIALIZED = 4,
  ErrorCode_ERR_NOT_CALIBRATED = 5,
  ErrorCode_ERR_CANCELLED = 6,
  ErrorCode_MIN = ErrorCode_ERR_OTHER,
  ErrorCode_MAX = ErrorCode_ERR_CANCELLED
};

inline const ErrorCode (&EnumValuesErrorCode())[7] {
  static const ErrorCode values[] = {
    ErrorCode_ERR_OTHER,
    ErrorCode_ERR_MALFORMED_REQUEST,
    ErrorCode_ERR_OUT_OF_RANGE,
    ErrorCode_ERR_INVALID_JOINT,
    ErrorCode_ERR_NOT_INITIALIZED,
    ErrorCode_ERR_NOT_CALIBRATED,
    ErrorCode_ERR_CANCELLED
  };
  return values;
}

inline const char * const *EnumNamesErrorCode() {
  static const char * const names[8] = {
    "ERR_OTHER",
    "ERR_MALFORMED_REQUEST",
    "ERR_OUT_OF_RANGE",
    "ERR_INVALID_JOINT",
    "ERR_NOT_INITIALIZED",
    "ERR_NOT_CALIBRATED",
    "ERR_CANCELLED",
    nullptr
  };
  return names;
}

inline const char *EnumNameErrorCode(ErrorCode e) {
  if (::flatbuffers::IsOutRange(e, ErrorCode_ERR_OTHER, ErrorCode_ERR_CANCELLED)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesErrorCode()[index];
}

}  // namespace CobotMsgs

#endif  // FLATBUFFERS_GENERATED_ERRORS_COBOTMSGS_H_
