/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_COBOT_ERRORS_PB_H_INCLUDED
#define PB_COBOT_ERRORS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Common error codes for all COBOT communication */
typedef enum _cobot_ErrorCode {
    /* An error that does not fit into any other category. */
    cobot_ErrorCode_ERR_OTHER = 0,
    /* The request was malformed and could not be parsed. */
    cobot_ErrorCode_ERR_MALFORMED_REQUEST = 1,
    /* A value was out of its expected range. */
    cobot_ErrorCode_ERR_OUT_OF_RANGE = 2,
    /* The requested joint does not exist. */
    cobot_ErrorCode_ERR_INVALID_JOINT = 3,
    /* The request could not be fulfilled because the COBOT is not initialized. */
    cobot_ErrorCode_ERR_NOT_INITIALIZED = 4,
    /* The request could not be fulfilled because a joint has not been calibrated. */
    cobot_ErrorCode_ERR_NOT_CALIBRATED = 5,
    /* The operation was cancelled by another operation. */
    cobot_ErrorCode_ERR_CANCELLED = 6
} cobot_ErrorCode;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _cobot_ErrorCode_MIN cobot_ErrorCode_ERR_OTHER
#define _cobot_ErrorCode_MAX cobot_ErrorCode_ERR_CANCELLED
#define _cobot_ErrorCode_ARRAYSIZE ((cobot_ErrorCode)(cobot_ErrorCode_ERR_CANCELLED+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
