/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "request.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cobot_Request, cobot_Request, AUTO)


PB_BIND(cobot_Request_Init, cobot_Request_Init, AUTO)


PB_BIND(cobot_Request_Calibrate, cobot_Request_Calibrate, AUTO)


PB_BIND(cobot_Request_Override, cobot_Request_Override, AUTO)


PB_BIND(cobot_Request_Override_NewAnglesEntry, cobot_Request_Override_NewAnglesEntry, AUTO)


PB_BIND(cobot_Request_GetJoints, cobot_Request_GetJoints, AUTO)


PB_BIND(cobot_Request_MoveTo, cobot_Request_MoveTo, AUTO)


PB_BIND(cobot_Request_MoveTo_MoveToConfig, cobot_Request_MoveTo_MoveToConfig, AUTO)


PB_BIND(cobot_Request_MoveTo_JointSettingsEntry, cobot_Request_MoveTo_JointSettingsEntry, AUTO)


PB_BIND(cobot_Request_MoveSpeed, cobot_Request_MoveSpeed, AUTO)


PB_BIND(cobot_Request_MoveSpeed_SpeedsEntry, cobot_Request_MoveSpeed_SpeedsEntry, AUTO)


PB_BIND(cobot_Request_Stop, cobot_Request_Stop, AUTO)


PB_BIND(cobot_Request_GoHome, cobot_Request_GoHome, AUTO)


PB_BIND(cobot_Request_Reset, cobot_Request_Reset, AUTO)


PB_BIND(cobot_Request_SetLogLevel, cobot_Request_SetLogLevel, AUTO)




