/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_COBOT_REQUEST_PB_H_INCLUDED
#define PB_COBOT_REQUEST_PB_H_INCLUDED
#include <pb.h>
#include "log.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _cobot_Request_RequestType {
    cobot_Request_RequestType_REQ_UNSPECIFIED_TYPE = 0,
    cobot_Request_RequestType_REQ_INIT = 1,
    cobot_Request_RequestType_REQ_CALIBRATE = 2,
    cobot_Request_RequestType_REQ_OVERRIDE = 3,
    cobot_Request_RequestType_REQ_GET_JOINTS = 4,
    cobot_Request_RequestType_REQ_MOVE_TO = 5,
    cobot_Request_RequestType_REQ_MOVE_SPEED = 6,
    cobot_Request_RequestType_REQ_STOP = 7,
    cobot_Request_RequestType_REQ_GO_HOME = 8,
    cobot_Request_RequestType_REQ_RESET = 9,
    cobot_Request_RequestType_REQ_SET_LOG_LEVEL = 10
} cobot_Request_RequestType;

/* Struct definitions */
/* Initialize the COBOT. This validates that the firmware version is correct and that the COBOT
 is ready to receive commands. Must be sent before any other request. */
typedef struct _cobot_Request_Init {
    /* The expected firmware version. If the firmware version does not match, the COBOT will not
 respond to any requests. */
    uint32_t expected_fw_version;
} cobot_Request_Init;

/* Calibrate the COBOT. This will move the COBOT until it hits the endstops and then set the
 proper zero and home positions. A joint must have been calibrated before it can be moved. */
typedef struct _cobot_Request_Calibrate {
    /* Bitfield of joints to calibrate. If a joint is not specified, it will not be calibrated. */
    uint32_t joints_bitfield;
} cobot_Request_Calibrate;

/* Override the COBOT's current position. This will set the current positions of the specified
 joints to the specified angles. This can be used for manual error correction. All joints will
 be stopped, including ones that are not specified in the request. */
typedef struct _cobot_Request_Override {
    /* Map of joint ID to angle. */
    pb_callback_t new_angles;
} cobot_Request_Override;

typedef struct _cobot_Request_Override_NewAnglesEntry {
    uint32_t key;
    float value;
} cobot_Request_Override_NewAnglesEntry;

/* Get the current positions of all joints. */
typedef struct _cobot_Request_GetJoints {
    char dummy_field;
} cobot_Request_GetJoints;

/* Move the COBOT to the specified position. This will move each joint to the specified angle
 at the specified speed. If a speed is omitted, the COBOT will automatically calculate an
 acceleration profile. Any in-progress move will be cancelled when the new move begins. All
 specified joints must have been previously calibrated. */
typedef struct _cobot_Request_MoveTo {
    /* Map of joint ID to joint settings. */
    pb_callback_t joint_settings;
} cobot_Request_MoveTo;

typedef struct _cobot_Request_MoveTo_MoveToConfig {
    /* The angle to move to (degrees from home). */
    float angle;
    /* The speed to move at (degrees per second). If omitted, the COBOT will automatically
 calculate an acceleration profile. */
    float speed;
} cobot_Request_MoveTo_MoveToConfig;

typedef struct _cobot_Request_MoveTo_JointSettingsEntry {
    uint32_t key;
    bool has_value;
    cobot_Request_MoveTo_MoveToConfig value;
} cobot_Request_MoveTo_JointSettingsEntry;

/* Move the COBOT's joints indefinitely at a specified speed. If a joint reaches an endstop, it
 will stop moving for safety reasons. Any in-progress move will be cancelled when the new move
 begins. All specified joints must have been previously calibrated. */
typedef struct _cobot_Request_MoveSpeed {
    /* Map of joint ID to speed (degrees per second). */
    pb_callback_t speeds;
} cobot_Request_MoveSpeed;

typedef struct _cobot_Request_MoveSpeed_SpeedsEntry {
    uint32_t key;
    float value;
} cobot_Request_MoveSpeed_SpeedsEntry;

/* Stop the specified joints. By default, joints are stopped smoothly. If the "immediate" flag
 is set, joints will stop immediately instead. If no joints are specified, all joints will
 stop. Any in-progress move will be cancelled. */
typedef struct _cobot_Request_Stop {
    /* If true, stop the joints immediately instead of smoothly. */
    bool immediate;
    /* Bitfield of joints to stop. If a joint is not specified, it will not be stopped. */
    uint32_t joints_bitfield;
} cobot_Request_Stop;

/* Move the specified joints to their home positions. Any in-progress move will be cancelled.
 All specified joints must have been previously calibrated. */
typedef struct _cobot_Request_GoHome {
    /* Bitfield of joints to move to their home positions. If a joint is not specified, it will not
 be moved. */
    uint32_t joints_bitfield;
} cobot_Request_GoHome;

/* Reset the COBOT. This will stop all joints and reset the COBOT's state. Any in-progress move
 will be cancelled. The COBOT will need to be initialized and calibrated again before it can
 be used. */
typedef struct _cobot_Request_Reset {
    char dummy_field;
} cobot_Request_Reset;

/* Set the log level. This will change the log level for the COBOT's internal logger. This should
 only be used for debugging, as it will affect performance. By default, the log level is set to
 INFO, which will log all INFO, WARNING, and ERROR messages. */
typedef struct _cobot_Request_SetLogLevel {
    /* The log level to set. */
    cobot_LogLevel log_level;
} cobot_Request_SetLogLevel;

/* Any request sent to the COBOT. A request contains a message ID, a request type, and a payload.
 The payload is a message that depends on the request type. */
typedef struct _cobot_Request {
    /* The message ID. This is used to match responses to requests. */
    uint32_t message_id;
    /* The request type. This determines the payload type. */
    cobot_Request_RequestType request_type;
    pb_size_t which_payload;
    union {
        cobot_Request_Init init; /* Payload for REQ_INIT */
        cobot_Request_Calibrate calibrate; /* Payload for REQ_CALIBRATE */
        cobot_Request_Override override; /* Payload for REQ_OVERRIDE */
        cobot_Request_GetJoints get_joints; /* Payload for REQ_GET_JOINTS */
        cobot_Request_MoveTo move_to; /* Payload for REQ_MOVE_TO */
        cobot_Request_MoveSpeed move_speed; /* Payload for REQ_MOVE_SPEED */
        cobot_Request_Stop stop; /* Payload for REQ_STOP */
        cobot_Request_GoHome go_home; /* Payload for REQ_GO_HOME */
        cobot_Request_Reset reset; /* Payload for REQ_RESET */
        cobot_Request_SetLogLevel set_log_level; /* Payload for REQ_SET_LOG_LEVEL */
    } payload;
} cobot_Request;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _cobot_Request_RequestType_MIN cobot_Request_RequestType_REQ_UNSPECIFIED_TYPE
#define _cobot_Request_RequestType_MAX cobot_Request_RequestType_REQ_SET_LOG_LEVEL
#define _cobot_Request_RequestType_ARRAYSIZE ((cobot_Request_RequestType)(cobot_Request_RequestType_REQ_SET_LOG_LEVEL+1))

#define cobot_Request_request_type_ENUMTYPE cobot_Request_RequestType














#define cobot_Request_SetLogLevel_log_level_ENUMTYPE cobot_LogLevel


/* Initializer values for message structs */
#define cobot_Request_init_default               {0, _cobot_Request_RequestType_MIN, 0, {cobot_Request_Init_init_default}}
#define cobot_Request_Init_init_default          {0}
#define cobot_Request_Calibrate_init_default     {0}
#define cobot_Request_Override_init_default      {{{NULL}, NULL}}
#define cobot_Request_Override_NewAnglesEntry_init_default {0, 0}
#define cobot_Request_GetJoints_init_default     {0}
#define cobot_Request_MoveTo_init_default        {{{NULL}, NULL}}
#define cobot_Request_MoveTo_MoveToConfig_init_default {0, 0}
#define cobot_Request_MoveTo_JointSettingsEntry_init_default {0, false, cobot_Request_MoveTo_MoveToConfig_init_default}
#define cobot_Request_MoveSpeed_init_default     {{{NULL}, NULL}}
#define cobot_Request_MoveSpeed_SpeedsEntry_init_default {0, 0}
#define cobot_Request_Stop_init_default          {0, 0}
#define cobot_Request_GoHome_init_default        {0}
#define cobot_Request_Reset_init_default         {0}
#define cobot_Request_SetLogLevel_init_default   {_cobot_LogLevel_MIN}
#define cobot_Request_init_zero                  {0, _cobot_Request_RequestType_MIN, 0, {cobot_Request_Init_init_zero}}
#define cobot_Request_Init_init_zero             {0}
#define cobot_Request_Calibrate_init_zero        {0}
#define cobot_Request_Override_init_zero         {{{NULL}, NULL}}
#define cobot_Request_Override_NewAnglesEntry_init_zero {0, 0}
#define cobot_Request_GetJoints_init_zero        {0}
#define cobot_Request_MoveTo_init_zero           {{{NULL}, NULL}}
#define cobot_Request_MoveTo_MoveToConfig_init_zero {0, 0}
#define cobot_Request_MoveTo_JointSettingsEntry_init_zero {0, false, cobot_Request_MoveTo_MoveToConfig_init_zero}
#define cobot_Request_MoveSpeed_init_zero        {{{NULL}, NULL}}
#define cobot_Request_MoveSpeed_SpeedsEntry_init_zero {0, 0}
#define cobot_Request_Stop_init_zero             {0, 0}
#define cobot_Request_GoHome_init_zero           {0}
#define cobot_Request_Reset_init_zero            {0}
#define cobot_Request_SetLogLevel_init_zero      {_cobot_LogLevel_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define cobot_Request_Init_expected_fw_version_tag 1
#define cobot_Request_Calibrate_joints_bitfield_tag 1
#define cobot_Request_Override_new_angles_tag    1
#define cobot_Request_Override_NewAnglesEntry_key_tag 1
#define cobot_Request_Override_NewAnglesEntry_value_tag 2
#define cobot_Request_MoveTo_joint_settings_tag  1
#define cobot_Request_MoveTo_MoveToConfig_angle_tag 1
#define cobot_Request_MoveTo_MoveToConfig_speed_tag 2
#define cobot_Request_MoveTo_JointSettingsEntry_key_tag 1
#define cobot_Request_MoveTo_JointSettingsEntry_value_tag 2
#define cobot_Request_MoveSpeed_speeds_tag       1
#define cobot_Request_MoveSpeed_SpeedsEntry_key_tag 1
#define cobot_Request_MoveSpeed_SpeedsEntry_value_tag 2
#define cobot_Request_Stop_immediate_tag         1
#define cobot_Request_Stop_joints_bitfield_tag   2
#define cobot_Request_GoHome_joints_bitfield_tag 1
#define cobot_Request_SetLogLevel_log_level_tag  1
#define cobot_Request_message_id_tag             1
#define cobot_Request_request_type_tag           2
#define cobot_Request_init_tag                   3
#define cobot_Request_calibrate_tag              4
#define cobot_Request_override_tag               5
#define cobot_Request_get_joints_tag             6
#define cobot_Request_move_to_tag                7
#define cobot_Request_move_speed_tag             8
#define cobot_Request_stop_tag                   9
#define cobot_Request_go_home_tag                10
#define cobot_Request_reset_tag                  11
#define cobot_Request_set_log_level_tag          12

/* Struct field encoding specification for nanopb */
#define cobot_Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  message_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    request_type,      2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,init,payload.init),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,calibrate,payload.calibrate),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,override,payload.override),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,get_joints,payload.get_joints),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,move_to,payload.move_to),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,move_speed,payload.move_speed),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,stop,payload.stop),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,go_home,payload.go_home),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,reset,payload.reset),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,set_log_level,payload.set_log_level),  12)
#define cobot_Request_CALLBACK NULL
#define cobot_Request_DEFAULT NULL
#define cobot_Request_payload_init_MSGTYPE cobot_Request_Init
#define cobot_Request_payload_calibrate_MSGTYPE cobot_Request_Calibrate
#define cobot_Request_payload_override_MSGTYPE cobot_Request_Override
#define cobot_Request_payload_get_joints_MSGTYPE cobot_Request_GetJoints
#define cobot_Request_payload_move_to_MSGTYPE cobot_Request_MoveTo
#define cobot_Request_payload_move_speed_MSGTYPE cobot_Request_MoveSpeed
#define cobot_Request_payload_stop_MSGTYPE cobot_Request_Stop
#define cobot_Request_payload_go_home_MSGTYPE cobot_Request_GoHome
#define cobot_Request_payload_reset_MSGTYPE cobot_Request_Reset
#define cobot_Request_payload_set_log_level_MSGTYPE cobot_Request_SetLogLevel

#define cobot_Request_Init_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   expected_fw_version,   1)
#define cobot_Request_Init_CALLBACK NULL
#define cobot_Request_Init_DEFAULT NULL

#define cobot_Request_Calibrate_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   joints_bitfield,   1)
#define cobot_Request_Calibrate_CALLBACK NULL
#define cobot_Request_Calibrate_DEFAULT NULL

#define cobot_Request_Override_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  new_angles,        1)
#define cobot_Request_Override_CALLBACK pb_default_field_callback
#define cobot_Request_Override_DEFAULT NULL
#define cobot_Request_Override_new_angles_MSGTYPE cobot_Request_Override_NewAnglesEntry

#define cobot_Request_Override_NewAnglesEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2)
#define cobot_Request_Override_NewAnglesEntry_CALLBACK NULL
#define cobot_Request_Override_NewAnglesEntry_DEFAULT NULL

#define cobot_Request_GetJoints_FIELDLIST(X, a) \

#define cobot_Request_GetJoints_CALLBACK NULL
#define cobot_Request_GetJoints_DEFAULT NULL

#define cobot_Request_MoveTo_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  joint_settings,    1)
#define cobot_Request_MoveTo_CALLBACK pb_default_field_callback
#define cobot_Request_MoveTo_DEFAULT NULL
#define cobot_Request_MoveTo_joint_settings_MSGTYPE cobot_Request_MoveTo_JointSettingsEntry

#define cobot_Request_MoveTo_MoveToConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    angle,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    speed,             2)
#define cobot_Request_MoveTo_MoveToConfig_CALLBACK NULL
#define cobot_Request_MoveTo_MoveToConfig_DEFAULT NULL

#define cobot_Request_MoveTo_JointSettingsEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  value,             2)
#define cobot_Request_MoveTo_JointSettingsEntry_CALLBACK NULL
#define cobot_Request_MoveTo_JointSettingsEntry_DEFAULT NULL
#define cobot_Request_MoveTo_JointSettingsEntry_value_MSGTYPE cobot_Request_MoveTo_MoveToConfig

#define cobot_Request_MoveSpeed_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  speeds,            1)
#define cobot_Request_MoveSpeed_CALLBACK pb_default_field_callback
#define cobot_Request_MoveSpeed_DEFAULT NULL
#define cobot_Request_MoveSpeed_speeds_MSGTYPE cobot_Request_MoveSpeed_SpeedsEntry

#define cobot_Request_MoveSpeed_SpeedsEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   key,               1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2)
#define cobot_Request_MoveSpeed_SpeedsEntry_CALLBACK NULL
#define cobot_Request_MoveSpeed_SpeedsEntry_DEFAULT NULL

#define cobot_Request_Stop_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     immediate,         1) \
X(a, STATIC,   SINGULAR, UINT32,   joints_bitfield,   2)
#define cobot_Request_Stop_CALLBACK NULL
#define cobot_Request_Stop_DEFAULT NULL

#define cobot_Request_GoHome_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   joints_bitfield,   1)
#define cobot_Request_GoHome_CALLBACK NULL
#define cobot_Request_GoHome_DEFAULT NULL

#define cobot_Request_Reset_FIELDLIST(X, a) \

#define cobot_Request_Reset_CALLBACK NULL
#define cobot_Request_Reset_DEFAULT NULL

#define cobot_Request_SetLogLevel_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    log_level,         1)
#define cobot_Request_SetLogLevel_CALLBACK NULL
#define cobot_Request_SetLogLevel_DEFAULT NULL

extern const pb_msgdesc_t cobot_Request_msg;
extern const pb_msgdesc_t cobot_Request_Init_msg;
extern const pb_msgdesc_t cobot_Request_Calibrate_msg;
extern const pb_msgdesc_t cobot_Request_Override_msg;
extern const pb_msgdesc_t cobot_Request_Override_NewAnglesEntry_msg;
extern const pb_msgdesc_t cobot_Request_GetJoints_msg;
extern const pb_msgdesc_t cobot_Request_MoveTo_msg;
extern const pb_msgdesc_t cobot_Request_MoveTo_MoveToConfig_msg;
extern const pb_msgdesc_t cobot_Request_MoveTo_JointSettingsEntry_msg;
extern const pb_msgdesc_t cobot_Request_MoveSpeed_msg;
extern const pb_msgdesc_t cobot_Request_MoveSpeed_SpeedsEntry_msg;
extern const pb_msgdesc_t cobot_Request_Stop_msg;
extern const pb_msgdesc_t cobot_Request_GoHome_msg;
extern const pb_msgdesc_t cobot_Request_Reset_msg;
extern const pb_msgdesc_t cobot_Request_SetLogLevel_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cobot_Request_fields &cobot_Request_msg
#define cobot_Request_Init_fields &cobot_Request_Init_msg
#define cobot_Request_Calibrate_fields &cobot_Request_Calibrate_msg
#define cobot_Request_Override_fields &cobot_Request_Override_msg
#define cobot_Request_Override_NewAnglesEntry_fields &cobot_Request_Override_NewAnglesEntry_msg
#define cobot_Request_GetJoints_fields &cobot_Request_GetJoints_msg
#define cobot_Request_MoveTo_fields &cobot_Request_MoveTo_msg
#define cobot_Request_MoveTo_MoveToConfig_fields &cobot_Request_MoveTo_MoveToConfig_msg
#define cobot_Request_MoveTo_JointSettingsEntry_fields &cobot_Request_MoveTo_JointSettingsEntry_msg
#define cobot_Request_MoveSpeed_fields &cobot_Request_MoveSpeed_msg
#define cobot_Request_MoveSpeed_SpeedsEntry_fields &cobot_Request_MoveSpeed_SpeedsEntry_msg
#define cobot_Request_Stop_fields &cobot_Request_Stop_msg
#define cobot_Request_GoHome_fields &cobot_Request_GoHome_msg
#define cobot_Request_Reset_fields &cobot_Request_Reset_msg
#define cobot_Request_SetLogLevel_fields &cobot_Request_SetLogLevel_msg

/* Maximum encoded size of messages (where known) */
/* cobot_Request_size depends on runtime parameters */
/* cobot_Request_Override_size depends on runtime parameters */
/* cobot_Request_MoveTo_size depends on runtime parameters */
/* cobot_Request_MoveSpeed_size depends on runtime parameters */
#define cobot_Request_Calibrate_size             6
#define cobot_Request_GetJoints_size             0
#define cobot_Request_GoHome_size                6
#define cobot_Request_Init_size                  6
#define cobot_Request_MoveSpeed_SpeedsEntry_size 11
#define cobot_Request_MoveTo_JointSettingsEntry_size 18
#define cobot_Request_MoveTo_MoveToConfig_size   10
#define cobot_Request_Override_NewAnglesEntry_size 11
#define cobot_Request_Reset_size                 0
#define cobot_Request_SetLogLevel_size           2
#define cobot_Request_Stop_size                  8

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
