/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "response.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cobot_Response, cobot_Response, AUTO)


PB_BIND(cobot_Response_Ack, cobot_Response_Ack, AUTO)


PB_BIND(cobot_Response_Error, cobot_Response_Error, AUTO)


PB_BIND(cobot_Response_Done, cobot_Response_Done, AUTO)


PB_BIND(cobot_Response_Joints, cobot_Response_Joints, AUTO)


PB_BIND(cobot_Response_Joints_PositionsEntry, cobot_Response_Joints_PositionsEntry, AUTO)




