#ifndef AR3_TEENSY_FIRMWARE__AR3_ERROR_H
#define AR3_TEENSY_FIRMWARE__AR3_ERROR_H

typedef enum {
  AR3_ERR_OK = 0,
  AR3_ERR_INVALID_COMMAND = 1,
  AR3_ERR_INVALID_ARG = 2,
  AR3_ERR_OOB = 3,
  AR3_ERR_NOT_CALIBRATED = 4,
  AR3_ERR_TIMEOUT = 5,
  AR3_ERR_PHYSICAL = 6,
  AR3_MALFORMED_ARG = 7,
  AR3_ERR_UNKNOWN = -1,
} ErrorCode;

#endif  // AR3_TEENSY_FIRMWARE__ERROR_H